### ISSUE TITLE
Piano data not found.

### ISSUE THREAD

**Issue by lyc105** [JTT94/filterflow#20]
In scripts/train_vrnn.py, the dataset ../data/data/piano_data/jsb.pkl cannot be found. Could you make this data available? Thanks!

**Comment by JTT94** [comment]
This experiment and setup was taken from https://arxiv.org/abs/1705.09279.

From their github:
echo "Downloading datasets into $1"
curl -s "http://www-etud.iro.umontreal.ca/~boulanni/Piano-midi.de.pickle" > $1/piano-midi.de.pkl
curl -s "http://www-etud.iro.umontreal.ca/~boulanni/Nottingham.pickle" > $1/nottingham.pkl
curl -s "http://www-etud.iro.umontreal.ca/~boulanni/MuseData.pickle" > $1/musedata.pkl
curl -s "http://www-etud.iro.umontreal.ca/~boulanni/JSB%20Chorales.pickle" > $1/jsb.pkl

**Comment by lyc105** [comment]
Thanks for sharing the data. One more question: the key term "train_mean" (line 110, train_vrnn.py) seems not in the original dataset. Is there any preprocessing for the data before running the code?

**Comment by JTT94** [comment]
We followed the preprocessing from the fivo paper, best to check there. 

The experiments can be carried out using their code in TF1 and replacing the resampling step with our resampling proxy with optimal transport.

Due to TF2 being under development at the time and some issues / bugs in TF2, we did the vrnn and robotic localisation in pytorch so I would not recommend using the current code here for these experiments. I thought I deleted the train_vrnn scripts as they were not final etc.

The hope was to have this library as an extensible library rather than for applications. So it should be easy to adapt to your experiments. 

Tensorflow has since improved and some other researchers have since adapted our code. See e.g. https://github.com/lll6924/vmpf and 
https://arxiv.org/abs/2106.10314. 

I do not intend to maintain the pytorch version so will not release it publicly. I have developed a Jax version and will migrate the experiments over once the follow up paper using this code base is published.
